DB_NAME = "database.db"

SECRET_KEY = 'jkj29USij290!js6*(4mn@9K2*$K'
SQLALCHEMY_DATABASE_URI = f'sqlite:///{DB_NAME}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
REMEMBER_COOKIE_SAMESITE = 'Lax'
UPLOAD_PROFILE_FOLDER = 'website/static/profile_images'
